### ISSUE TITLE
Getting "ZeroDivisionError: division by zero" in training

### ISSUE THREAD

**Issue by Ayushkumawat** [ShawkhIbneRashid/medical-images-sr#3]
![image](https://user-images.githubusercontent.com/76219349/216694577-99afe5d5-9025-4412-a1d1-66425f6f7b30.png)

I am getting ZeroDivisionError: division by zero while training the model in - "real_esrgan_notebook.ipynb" file

![image](https://user-images.githubusercontent.com/76219349/216694747-8e1db404-34c4-421c-9cca-834755fceb43.png)

This is the code I am running and it's in "real_esrgan_notebook.ipynb" file

I've replaced "realesrgan_dataset.py, realesrgan_model.py, and utils.py" in 'realesrgan' folder and also replaced "train_realesrgan_x4plus.yml" in 'options' folder under 'Real-ESRGAN' by the files you've uploaded. Is there anything else to be replaced? or do I have to edit the information in the file?

Also, is there any pattern or numbering in running those files? Like I first tried running 'real_esrgan_notebook.ipynb' and replaced those files in the directory, what's the order? and also what the dataset.ipynb file meant for?

**Comment by ShawkhIbneRashid** [comment]
You will have to edit the information in the .yml file according to your criteria. Take a look into this [resource](https://github.com/xinntao/Real-ESRGAN/blob/master/docs/Training.md#Finetune-Real-ESRGAN-on-your-own-dataset) to understand better which files to place under which folders and the options in the .yml file. The dataset.ipynb file generates 2D numpy arrays from the 3D .nii files. This way you can train the Real-ESRGAN model using the generated 2D arrays.

**Comment by Ayushkumawat** [comment]
![image](https://user-images.githubusercontent.com/76219349/216779452-7a489b77-6cf8-4504-90ee-8a3a2f64fb14.png)

Getting this error in "real_esrgan_notebook.ipynb" file
.
.
This was the code

![image](https://user-images.githubusercontent.com/76219349/216779501-cfb7adfc-f8cf-46c0-a145-2d165af942f7.png)

I don't know, why I am getting this error while installing modules

**Comment by ShawkhIbneRashid** [comment]
After cloning the repo and installing the packages, there will be a folder named realesrgan as shown in the screenshot here. Check if you have it. Also, check the repository of Real-ESRGAN https://github.com/xinntao/Real-ESRGAN
![image](https://user-images.githubusercontent.com/38233390/216789329-ae0b1be3-6880-456c-bbcd-c8a9adef8cf9.png)

**Comment by Ayushkumawat** [comment]
I don't know how, but that error got replaced by this new error in the same code line
![image](https://user-images.githubusercontent.com/76219349/216792141-e7c84d93-2f41-4b8e-b598-e3299bdb0a12.png)

**Comment by ShawkhIbneRashid** [comment]
Do you have this directory and did you clone the repository here? 
![image](https://user-images.githubusercontent.com/38233390/216792473-8690771a-3458-4fdb-8bbf-d1ed232f37bb.png)

**Comment by Ayushkumawat** [comment]
It helped me, I didn't know how some files were missing from the folder even after cloning, but I recloned the files, and it worked for me. Thanks👍
